trigger:
- main

resources:
- repo: self

variables:
  dockerRegistryServiceConnection: '4759b140-0ed4-49f4-ac9a-6196c134351c'
  imageRepository: 'varunkalrapipelinesjavascriptdocker'
  containerRegistry: 'lakhwancontainer.azurecr.io'
  dockerfilePath: '**/Dockerfile'
  tag: '$(Build.BuildId)'
  imagePullSecret: 'lakhwancontainer37869902-auth'
  vmImageName: 'ubuntu-latest'

pool:
  vmImage: $(vmImageName)

steps:
- displayName: Build and Push Image
  steps:
  - task: Docker@2
    displayName: Build and Push Docker Image
    inputs:
      command: buildAndPush
      repository: $(imageRepository)
      dockerfile: $(dockerfilePath)
      containerRegistry: $(dockerRegistryServiceConnection)
      tags: |
        $(tag)

  - publish: manifests
    artifact: manifests

- displayName: Deploy to AKS
  dependsOn: Build
  steps:
  - task: KubernetesManifest@0
    displayName: Create imagePullSecret
    inputs:
      action: createSecret
      secretName: $(imagePullSecret)
      dockerRegistryEndpoint: $(dockerRegistryServiceConnection)

  - task: KubernetesManifest@0
    displayName: Deploy to Kubernetes Cluster
    inputs:
      action: deploy
      manifests: |
        $(Pipeline.Workspace)/manifests/deployment.yml
        $(Pipeline.Workspace)/manifests/service.yml
      imagePullSecrets: |
        $(imagePullSecret)
      containers: |
        $(containerRegistry)/$(imageRepository):$(tag)
